name: Build Android APK

on: 
  push:
    branches:
      - main # Ou la branche principale de votre projet, par exemple 'master'

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Utilisez une version LTS de Node.js

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # Version de Java compatible avec Android

    - name: Install npm dependencies
      run: npm install

    - name: Clean Capacitor web assets
      run: rm -rf www

    - name: Clean Capacitor Android project
      run: npx cap clean android

    - name: Sync Capacitor with Android project
      run: npx cap sync android

    - name: Clean Android Gradle build
      run: cd android && ./gradlew clean

    - name: Build Android Debug APK
      run: cd android && ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
